import sqlite3
from pathlib import Path

# backend/app/core/db.py
PROJECT_ROOT = Path(__file__).resolve().parents[3]
DB_PATH = PROJECT_ROOT / "backend" / "data" / "smokwit_totem.db"


def get_conn() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH), timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def init_db() -> None:
    conn = get_conn()
    conn.execute("PRAGMA journal_mode=WAL;")
    conn.execute("PRAGMA synchronous=NORMAL;")
    cur = conn.cursor()

    # 1) Questions table (content)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS questions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        text TEXT NOT NULL,
        answer_a TEXT NOT NULL,
        answer_b TEXT NOT NULL,
        correct TEXT NOT NULL CHECK (correct IN ('A','B')),
        fact TEXT NOT NULL,
        is_active INTEGER NOT NULL DEFAULT 1
    );
    """)

    # 2) Answer logs
    cur.execute("""
    CREATE TABLE IF NOT EXISTS answer_logs (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        question_id INTEGER NOT NULL,
        chosen TEXT NOT NULL CHECK (chosen IN ('A','B')),
        is_correct INTEGER NOT NULL CHECK (is_correct IN (0,1)),
        created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),
        FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE
    );
    """)

    # 3) Legacy QR scans (keep for compatibility)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS qr_scans (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        totem_id TEXT NOT NULL,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        user_agent TEXT,
        ip_hash TEXT
    );
    """)

    # 4) ✅ New unified events table (analytics source of truth)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS totem_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        totem_id TEXT NOT NULL,
        mode TEXT NOT NULL,               -- quiz | discussion | chatbot
        event_type TEXT NOT NULL,         -- VISIT | QR_SCAN | QR_INTENT | COMPLETE | ...
        session_id TEXT,                  -- generated by totem on mode entry
        scenario_id TEXT,
        offer_id TEXT,
        user_agent TEXT,
        ip_hash TEXT
    );
    """)

    # Indexes
    cur.execute("CREATE INDEX IF NOT EXISTS idx_answer_logs_qid ON answer_logs(question_id);")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_answer_logs_time ON answer_logs(created_at);")

    cur.execute("CREATE INDEX IF NOT EXISTS idx_qr_scans_totem ON qr_scans(totem_id);")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_qr_scans_time ON qr_scans(created_at);")

    cur.execute("CREATE INDEX IF NOT EXISTS idx_events_time ON totem_events(created_at);")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_events_mode_type ON totem_events(mode, event_type);")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_events_session ON totem_events(session_id);")

    conn.commit()
    conn.close()


def seed_if_empty() -> None:
    conn = get_conn()
    cur = conn.cursor()

    row = cur.execute("SELECT COUNT(*) AS c FROM questions;").fetchone()
    count = int(row["c"]) if row else 0

    if count == 0:
        cur.executemany("""
        INSERT INTO questions (text, answer_a, answer_b, correct, fact)
        VALUES (?, ?, ?, ?, ?);
        """, [
            (
                "Tobacco is the cause of how many deaths each year worldwide?",
                "Around 8 million",
                "Around 5 million",
                "A",
                "Tobacco causes over 8 million deaths each year, including .3 million non-smokers exposed to secondhand smoke. (WHO)"
            ),
            (
                "How many chemicals are in cigarette smoke?",
                "Around 2,500",
                "Around 7,000",
                "B",
                "Cigarette smoke contains over 7,000 chemicals, hundreds of which are toxic and about 70 can cause cancer. (CDC)"
            ),
            (
                "Is nicotine as addictive as other hard drugs?",
                "Yes",
                "No",
                "A",
                "Nicotine is proven to be as addictive as substances like heroin and cocaine. (NIDA)"
            ),
        ])

        conn.commit()

    conn.close()
